import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Studio 9 Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/s9incLOGOsml.png" />
      </Head>

      <main>
      </main>

      <footer>
      </footer>
    </div>
  )
}
